spring.application.name=smartbite-main-service
server.port=8081

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smartbite_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

wallet.service.base-url=${WALLET_SERVICE_URL:http://localhost:8082}
internal.api.key=${INTERNAL_API_KEY}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
