spring.application.name=auth_service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/smartbite_auth_db

spring.datasource.username=root
spring.datasource.password=root



spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#jwt configgg.
jwt.secret=smartbiteSecretKeyForJwtAuthentication123456789
jwt.expiration =864000000